services:
  postgres:
    image: postgres:18
    container_name: steda
    restart: "no"

    environment:
      POSTGRES_USER: steda
      POSTGRES_PASSWORD: steda
      POSTGRES_DB: steda_test
      PGDATA: /var/lib/postgresql/18/docker

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - steda-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

    command:
      [
        "postgres",
        "-c", "log_connections=on",
        "-c", "log_disconnections=on",
        "-c", "log_min_duration_statement=250ms"
      ]

volumes:
  steda-data:
