//! Public queue, task, retry, and worker types.

use std::time::Duration;

use serde::{Deserialize, Serialize, de::DeserializeOwned};
use serde_json::{Map, Value as JsonValue};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::error::Result;

/// JSON value type for task parameters, headers, checkpoints, and results.
pub type Json = JsonValue;

/// JSON object type for headers and option payloads.
pub type JsonObject = Map<String, Json>;

/// Steda queue task identifier.
///
/// Generated by Postgres as `UUIDv7`.
pub type TaskId = Uuid;

/// Steda queue run identifier.
///
/// Generated by Postgres as `UUIDv7`.
pub type RunId = Uuid;

/// UTC timestamp type used for Postgres `TIMESTAMPTZ` values.
pub type Timestamp = OffsetDateTime;

/// Retry strategy for failed tasks.
///
/// Each variant is canonical by construction: fixed retries carry only a delay,
/// exponential retries carry their required timing parameters, and disabled retries
/// carry no timing fields. `PostgreSQL` remains authoritative for numeric validation.
///
/// ```
/// use steda::RetryStrategy;
///
/// let strategy = RetryStrategy::exponential(5.0, 2.0, Some(300.0));
/// assert!(matches!(strategy, RetryStrategy::Exponential { .. }));
/// ```
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum RetryStrategy {
    /// Retry after a fixed delay.
    Fixed {
        /// Delay before retrying, in seconds.
        base_seconds: f64,
    },

    /// Retry with exponential backoff.
    Exponential {
        /// Initial delay before retrying, in seconds.
        base_seconds: f64,
        /// Exponential multiplier.
        factor: f64,
        /// Optional upper bound for computed delay, in seconds.
        #[serde(skip_serializing_if = "Option::is_none")]
        max_seconds: Option<f64>,
    },

    /// Do not retry failed runs.
    None,
}

impl RetryStrategy {
    /// Create a fixed retry strategy.
    pub const fn fixed(base_seconds: f64) -> Self {
        Self::Fixed { base_seconds }
    }

    /// Create an exponential retry strategy.
    pub const fn exponential(base_seconds: f64, factor: f64, max_seconds: Option<f64>) -> Self {
        Self::Exponential { base_seconds, factor, max_seconds }
    }

    /// Disable retries.
    pub const fn none() -> Self {
        Self::None
    }
}

/// Durable cancellation deadlines for one logical task.
///
/// `max_delay` is measured from enqueue until the first start and no longer applies once the task
/// has begun. `max_duration` is measured from the first start across the remainder of the logical
/// task, including retries and durable sleeps. Values are whole seconds evaluated against
/// `PostgreSQL`'s authoritative clock.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct CancellationPolicy {
    /// Maximum duration in seconds from first start.
    #[serde(rename = "max_duration", skip_serializing_if = "Option::is_none")]
    pub max_duration: Option<i64>,

    /// Maximum delay in seconds before first start.
    #[serde(rename = "max_delay", skip_serializing_if = "Option::is_none")]
    pub max_delay: Option<i64>,
}

/// Options for spawning a task.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct SpawnConfig {
    /// Maximum number of retry attempts.
    #[serde(rename = "max_attempts", skip_serializing_if = "Option::is_none")]
    pub max_attempts: Option<i32>,

    /// Retry strategy.
    #[serde(rename = "retry_strategy", skip_serializing_if = "Option::is_none")]
    pub retry_strategy: Option<RetryStrategy>,

    /// Custom headers for the task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<JsonObject>,

    /// Cancellation policy.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancellation: Option<CancellationPolicy>,

    /// Idempotency key for deduplicating task creation.
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
}

/// Internal result of spawning a logical task.
#[derive(Debug, Clone, Copy)]
pub(crate) struct SpawnResult {
    /// Unique logical task identifier.
    pub id: TaskId,

    /// Whether this was a new task, false if deduplicated.
    pub created: bool,
}

/// Optional persisted queue-maintenance policy overrides.
///
/// `None` leaves that field at its current/default value. New queues default to a 30-day terminal
/// task TTL and a maximum of 1,000 logical-task deletions per cleanup pass.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct QueuePolicyOptions {
    /// Terminal task cleanup TTL.
    pub cleanup_ttl: Option<Duration>,

    /// Maximum rows cleaned per cleanup pass.
    pub cleanup_limit: Option<i32>,
}

/// Queue maintenance policy snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QueuePolicy {
    /// Queue name.
    pub name: String,

    /// Terminal task cleanup TTL.
    pub cleanup_ttl: Duration,

    /// Maximum cleanup rows per pass.
    pub cleanup_limit: i32,
}

/// Result of one automatic cleanup pass for a queue.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QueueCleanup {
    /// Queue name.
    pub name: String,

    /// Number of terminal tasks deleted.
    pub tasks_deleted: i32,
}

/// Task result state.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum TaskResultState {
    /// Task is waiting to run.
    Pending,

    /// Task is currently running.
    Running,

    /// Task is sleeping until a later time.
    Sleeping,

    /// Task completed successfully.
    Completed,

    /// Task failed terminally.
    Failed,

    /// Task was cancelled.
    Cancelled,
}

/// Current task result snapshot.
///
/// Completion and failure payloads can be deserialized directly from the snapshot:
///
/// ```
/// use steda::{TaskResultSnapshot, TaskResultState};
/// use serde_json::json;
///
/// let snapshot = TaskResultSnapshot::Completed { result: json!({ "count": 3 }) };
/// assert_eq!(snapshot.state(), TaskResultState::Completed);
/// assert!(snapshot.is_terminal());
/// assert_eq!(snapshot.result::<serde_json::Value>()?, Some(json!({ "count": 3 })));
/// # Ok::<(), steda::Error>(())
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "state", rename_all = "lowercase")]
pub enum TaskResultSnapshot {
    /// Task is waiting to run.
    Pending,

    /// Task is currently running.
    Running,

    /// Task is sleeping until a later time.
    Sleeping,

    /// Task completed successfully.
    Completed {
        /// Completion payload.
        result: Json,
    },

    /// Task failed terminally.
    Failed {
        /// Failure payload.
        failure: Json,
    },

    /// Task was cancelled.
    Cancelled,
}

impl TaskResultSnapshot {
    /// State without payload.
    pub const fn state(&self) -> TaskResultState {
        match self {
            Self::Pending => TaskResultState::Pending,
            Self::Running => TaskResultState::Running,
            Self::Sleeping => TaskResultState::Sleeping,
            Self::Completed { .. } => TaskResultState::Completed,
            Self::Failed { .. } => TaskResultState::Failed,
            Self::Cancelled => TaskResultState::Cancelled,
        }
    }

    /// Whether this snapshot is terminal.
    pub const fn is_terminal(&self) -> bool {
        matches!(self, Self::Completed { .. } | Self::Failed { .. } | Self::Cancelled)
    }

    /// Deserialize the completion payload when this snapshot is completed.
    ///
    /// # Errors
    ///
    /// Returns an error if the completion payload cannot be deserialized.
    pub fn result<T: DeserializeOwned>(&self) -> Result<Option<T>> {
        match self {
            Self::Completed { result } => Ok(Some(serde_json::from_value(result.clone())?)),
            _ => Ok(None),
        }
    }

    /// Deserialize the failure payload when this snapshot is failed.
    ///
    /// # Errors
    ///
    /// Returns an error if the failure payload cannot be deserialized.
    pub fn failure<T: DeserializeOwned>(&self) -> Result<Option<T>> {
        match self {
            Self::Failed { failure } => Ok(Some(serde_json::from_value(failure.clone())?)),
            _ => Ok(None),
        }
    }
}

/// A claimed task ready for execution.
#[derive(Debug, Clone)]
pub(crate) struct ClaimedTask {
    /// Claimed run identifier.
    pub(crate) run_id: RunId,

    /// Logical task identifier.
    pub(crate) id: TaskId,

    /// Registered task name.
    pub(crate) name: String,

    /// Attempt number for this run.
    pub(crate) attempt: i32,

    /// Task parameters.
    pub(crate) params: Json,

    /// Task headers.
    pub(crate) headers: Option<JsonObject>,
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::TaskResultSnapshot;

    #[test]
    fn task_result_snapshot_serializes_with_state_tag() {
        let snapshot = TaskResultSnapshot::Completed { result: json!({"ok": true}) };
        assert_eq!(
            serde_json::to_value(snapshot).unwrap(),
            json!({"state": "completed", "result": {"ok": true}})
        );
    }
}
